"""
Snakemake file for downstream analysis of 2M downsampled samples.

load modules:

    ml bioinfo-tools snakemake

sbatch command:
    
    sbatch -A ngi2016004 -J down_qc -n 12 -p core -t 1-00:00:00 --wrap "snakemake -p -j 12 --use-singularity -k --rerun-incomplete" --mail-user phojer@kth.se --mail-type ALL
"""
from snakemake.utils import min_version

min_version("6.0")

configfile: "workflow_config.yaml"


wildcard_constraints:
    sample = "|".join(config["samples"]),


rule all:
    input:
        "multiqc_report.html",
        expand("mosdepth_100kb/bedgraph/{sample}.regions.bedgraph", sample=config["samples"]),
        "chimeric_reads/counts.txt",
        "ref.non_n.count.txt",


def get_cram(sample):
    return f"{config['cram_path']}/{sample}/{sample}.md.cram" 


rule picard_nonn_fasta:
    output:
        "ref.non_n.count.txt"
    singularity: config["containers"]["picard"]
    log: "ref.non_n.count.txt.log"
    params:
        fasta = config["fasta"]
    shell:
        "picard NonNFastaSize"
        " I={params.fasta}"
        " O={output}"
        " &> {log}"


rule picard_gc_bias:
    input:
        cram = lambda wc: get_cram(wc.sample)
    output:
        txt1 = "picard/{sample}.gc_bias_metrics.txt",
        txt2 = "picard/{sample}.gc_summary_metrics.txt",
        pdf = "picard/{sample}.gc_bias_metrics.pdf"
    log: "picard/{sample}.gc_bias_metrics.txt.log"
    singularity: config["containers"]["picard"]
    params:
        fasta = config["fasta"]
    shell:
        "picard CollectGcBiasMetrics"
        " I={input.cram}"
        " O={output.txt1}"
        " CHART={output.pdf}"
        " S={output.txt2}"
        " R={params.fasta}"
        " &> {log}"


# Chimera 


rule chimeric_reads:
    input:
        cram = lambda wc: get_cram(wc.sample)
    output:
        txt = "chimeric_reads/{sample}.txt"
    singularity: config["containers"]["samtools"]
    params:
        max_len = 100_000,
        fasta = config["fasta"]
    shell:
        "samtools view"
        " -q 60" # Minimum mapping quality of 20
        " -F 0x4" # Exclude unmapped reads
        " -F 0x8" # Exclude mate unmapped
        " -F 0x800" # Exclude supplementary alignments
        " -e 'refid != mrefid || sqrt(pow(tlen,2)) >= {params.max_len}'"
        " -c"
        " -T {params.fasta}"
        " {input.cram}"
        " &> {output.txt}"


rule all_reads:
    input:
        cram = lambda wc: get_cram(wc.sample)
    output:
        txt = "chimeric_reads/{sample}.all.txt"
    log: "chimeric_reads/{sample}.all.txt.log"
    singularity: config["containers"]["samtools"]
    params:
        fasta = config["fasta"]
    shell:
        "samtools view"
        " -q 60" # Minimum mapping quality of 20
        " -F 0x4" # Exclude unmapped reads
        " -F 0x8" # Exclude mate unmapped
        " -F 0x800" # Exclude supplementary alignments
        " -c"
        " -T {params.fasta}"
        " {input.cram}"
        " &> {output.txt}"


rule count_reads:
    input:
        all = expand("chimeric_reads/{sample}.txt", sample=config["samples"]),
        chimera = expand("chimeric_reads/{sample}.all.txt", sample=config["samples"]),
    output:
        "chimeric_reads/counts.txt"
    run:
        with open(output[0], "w") as f:
            print("sample\tall_reads\tchimeric_reads", file=f)
            for sample in config["samples"]:
                all = int(open(f"chimeric_reads/{sample}.all.txt").read().strip())
                chimera = int(open(f"chimeric_reads/{sample}.txt").read().strip())
                print(f"{sample}\t{all}\t{chimera}", file=f)


# Coverage


mosdepth_ext = [
    ".mosdepth.summary.txt", 
    ".regions.bed.gz",
    ".mosdepth.global.dist.txt",
    ".mosdepth.region.dist.txt"
]


rule mosdepth:
    input:
        cram = lambda wc: get_cram(wc.sample)
    output:
        multiext("mosdepth/{sample}", *mosdepth_ext)
    singularity: config["containers"]["mosdepth"]
    log: "mosdepth/{sample}.mosdepth.log"
    params:
        prefix = "mosdepth/{sample}",
        ref = config["fasta"],
    shell:
        "MOSDEPTH_PRECISION=5"
        " mosdepth"
        " --no-per-base"
        " --fast-mode"
        " --fasta {params.ref}"
        " -b 1000" # Bins of 1000 bp
        " --mapq 20" # Minimum mapping quality of 20
        " {params.prefix}"
        " {input.cram}"
        " &> {log}"


rule mosdepth_100kb:
    input:
        cram = lambda wc: get_cram(wc.sample)
    output:
        "mosdepth_100kb/{sample}.regions.bed.gz",
        temp(multiext("mosdepth_100kb/{sample}", *[ext for ext in mosdepth_ext if ext != ".regions.bed.gz"]))
    singularity: config["containers"]["mosdepth"]
    log: "mosdepth_100kb/{sample}.mosdepth.log"
    params:
        prefix = "mosdepth_100kb/{sample}",
        ref = config["fasta"],
    shell:
        "MOSDEPTH_PRECISION=5"
        " mosdepth"
        " --no-per-base"
        " --fast-mode"
        " --fasta {params.ref}"
        " -b 100000" # Bins of 100 kbp
        " --mapq 20" # Minimum mapping quality of 20
        " {params.prefix}"
        " {input.cram}"
        " &> {log}"


rule bed_to_bedgraph:
    input:
        bed = "mosdepth_100kb/{sample}.regions.bed.gz",
    output:
        bedgrapgh = "mosdepth_100kb/bedgraph/{sample}.regions.bedgraph"
    shell:
        "zcat {input.bed}"
        " | awk '{{OFS=\"\\t\"; print $1,$2,$3,$4}}'"
        " > {output.bedgrapgh}"


# Create BAM


rule cram_to_bam:
    input:
        cram = lambda wc: get_cram(wc.sample)
    output:
        bam = "bam/{sample}.bam"
    log: "bam/{sample}.bam.log"
    singularity: config["containers"]["samtools"]
    threads: 2
    params:
        ref = config["fasta"],
    shell:
        "samtools view"
        " -@ {threads}"
        " -f 2" # Only properly paired reads
        " -F 0x800" # Exclude supplementary alignments
        " -bh"
        " -T {params.ref}"
        " {input.cram}"
        " -o {output.bam}"
        " &> {log}"


#
# GC extrap
#

rule bam_to_bed:
    input:
        bam = "bam/{sample}.bam"
    output:
        bed = "bam/{sample}.bed"
    log: "bam/{sample}.bed.log"
    threads: 4
    params: 
        bedtools = f'singularity exec {config["containers"]["bedtools"]} bedtools',
        samtools = f'singularity exec {config["containers"]["samtools"]} samtools'
    shell:
        "{params.samtools} sort -n"
        " -@ {threads}"
        " -u"
        " {input.bam}"
        " -T $TMPDIR/{wildcards.sample}"
        " 2> {log}"
        " | "
        "{params.bedtools} bamtobed"
        " -i stdin"
        " -bedpe"
        " 2>> {log}"
        " | "
        "cut -f 1,2,5"
        " | "
        "sort -k 1,1 -k 2,2n -k 3,3n"
        " > {output.bed}"


rule preseq_gc_extrap:
    # docs: https://preseq.readthedocs.io/en/latest/
    input:
        bed = "bam/{sample}.bed",
    output:
        txt = touch("preseq/{sample}.gc_extrap.txt")
    log: "preseq/{sample}.gc_extrap.txt.log"
    singularity: config["containers"]["preseq"]
    shell:
        "preseq gc_extrap"
        " -o {output.txt}"
        " -bed"
        " -v"
        " -e 100000000000" # Extrapolate to 100B bases -> 333 M reads (2x150)
        " -s 1000000000" # Step size 1B bases -> 3.3M reads
        #" -D" # Defects mode
        " {input.bed}"
        " &> {log}"


rule multiqc_sample_names:
    input:
        tsv = "../../../sample_info.tsv"
    output:
        tsv = "multiqc_sample_names.tsv"
    shell:
        "cut -f -2 {input.tsv}"
        " > {output.tsv}"


rule multiqc:
    input:
        expand("picard/{sample}.gc_bias_metrics.txt", sample=config["samples"]),
        expand("mosdepth/{sample}.mosdepth.summary.txt", sample=config["samples"]),
        expand("preseq/{sample}.gc_extrap.txt", sample=config["samples"]),
        tsv = "multiqc_sample_names.tsv",
    output:
        data = directory("multiqc_data"),
        html = "multiqc_report.html"
    log: "multiqc_report.html.log" 
    singularity: config["containers"]["multiqc"]
    shell:
        "multiqc"
        " -m picard"
        " -m mosdepth"
        " -m preseq"
        " --sample-names {input.tsv}"
        " ."
        " -v"
        " &> {log}"
