"""
Snakemake file for downstream analysis of 40M downsampled samples.

load modules:

    ml bioinfo-tools snakemake

sbatch command:
    
    sbatch -A ngi2016004 -J down_40M -n 22 -p core -t 1-00:00:00 --wrap "snakemake -p -j 22 --use-singularity -k --rerun-incomplete" --mail-user phojer@kth.se --mail-type ALL
"""

from snakemake.utils import min_version

min_version("6.0")

configfile: "workflow_config.yaml"

ftypes = ["", ".filtered", ".call", ".cnv"]

wildcard_constraints:
    sample = "|".join(config["samples"]),
    ftype = "|".join(ftypes)

rule all:
    input:
        "multiqc_report.html",
        expand("mosdepth_100kb/bedgraph/{sample}.regions.bedgraph", sample=config["samples"]),
        expand("cnvkit/{sample}/{sample}.regions.cns", sample=config["samples"]),
        expand("cnvkit/heatmap_GRCh38{ftype}_mqc.png", ftype=ftypes),
        expand("cnvkit/{sample}/{sample}.regions.filtered.bintest.cns", sample=config["samples"]),
        expand("cnvkit/{sample}/{sample}.regions.log2.bedgraph", sample=config["samples"]),
        "cnvkit/metrics.tsv",
        expand("cnvkit/GRCh38{ftype}.seg", ftype=ftypes),
        expand("cnvkit/{sample}/{sample}.regions{ftype}.cns", sample=config["samples"], ftype=ftypes),
        expand("cnvkit/{sample}/{sample}.regions{ftype}.vcf", sample=config["samples"], ftype=ftypes),
        expand("cnvkit/{sample}/{sample}.regions{ftype}.scatter.png", sample=config["samples"], ftype=ftypes),
        "chimeric_reads/counts.txt",
        "ref.non_n.count.txt",


module main_workflow:
    snakefile:
        # here, plain paths, URLs and the special markers for code hosting providers (see below) are possible.
        "../../downsample_qc/downstream_qc/Snakefile"
    config: config

use rule * from main_workflow exclude all as main_*
