"""
Snakemake file for downstream analysis of 2M downsampled samples.

load modules:

    ml bioinfo-tools snakemake

sbatch command:
    
    sbatch -A ngi2016004 -J contam -n 12 -p core -t 1-00:00:00 --wrap "snakemake -p -j 12 --use-singularity -k --rerun-incomplete" --mail-user phojer@kth.se --mail-type ALL
"""

samples = [
    "P33410_1001",
    "P33410_1002",
    "P33410_1003",
    "P33410_1004",
    "P33410_1005",
    "P33410_1006",
    "P33410_1008",
    "P33410_1009",
    "P33410_1010",
    "P33410_1011",
    "P33410_1012",
    "P33410_1013",
    "P33410_1014",
    "P33410_1015",
    "P33410_1016",
    "P33410_1017",
    "P33410_1018",
    "P33410_1019",
    "P33410_1020",
    "P33410_1021",
    "P33410_1022",
    "P33410_1024",
]

#kraken_db = "../../../resources/kraken2/k2_standard_08gb_20241228.tar.gz"
#kraken_db = "/vulpes/common/data/Kraken2_data/prebuilt/k2_standard_16gb_20240112" # 16Gb --> 3 cores
kraken_db = "/vulpes/common/data/Kraken2_data/prebuilt/k2_standard_20240112" # 72Gb --> 10 cores

# Containers 
bbmap = "/vulpes/ngi/containers/biocontainers/singularity-bbmap-39.01--h5c4e2a8_0.img"
samtools = "/vulpes/common/ngi/containers/biocontainers/singularity-samtools-1.19.2--h50ea8bc_0.img"
kraken2 = "/vulpes/ngi/containers/biocontainers/depot.galaxyproject.org-singularity-kraken2-2.1.1--pl526hc9558a2_0.img"
multiqc = "/vulpes/common/ngi/containers/biocontainers/singularity-multiqc-1.21--pyhdfd78af_0.img"
fastqc = "/vulpes/ngi/containers/biocontainers/singularity-fastqc-0.12.1--hdfd78af_0.img"


rule all:
    input:
        #expand("fastqs/{sample}_{nr}.fastq.gz", sample=samples, nr=[1,2]),
        expand("kraken2/{sample}.report", sample=samples),
        "multiqc_report.html"


rule samtools_get_umapped:
    input:
        cram = "../sarek_GRCh38/outdir/preprocessing/markduplicates/{sample}/{sample}.md.cram"
    output:
        fastq1 = "fastqs/{sample}_1.fastq.gz",
        fastq2 = "fastqs/{sample}_2.fastq.gz"
    singularity: samtools
    params:
        fasta = "/sw/data/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa"
    shell:
        # Extract unmapped pairs (read and mate unmapped)
        "samtools view -f 12 -T {params.fasta} -uh {input.cram}"
        " | "
        # Sort by name
        "samtools sort -n -u"
        " | "
        # Convert to paired FASTQs
        "samtools fastq -1 {output.fastq1} -2 {output.fastq2} -0 /dev/null -s /dev/null -n"


rule bbduk_filter_low_complexity:
    input:
        fastq1 = "fastqs/{sample}_1.fastq.gz",
        fastq2 = "fastqs/{sample}_2.fastq.gz"
    output:
        fastq1 = "fastqs/{sample}_1.filtered.fastq.gz",
        fastq2 = "fastqs/{sample}_2.filtered.fastq.gz"
    log: "fastqs/{sample}_1.filtered.fastq.gz.log"
    singularity: bbmap
    params:
        entropy=0.3,
        entropywindow=50,
    shell:
        "bbduk.sh"
        " entropy={params.entropy}"
        " entropywindow={params.entropywindow}"
        " in1={input.fastq1}"
        " in2={input.fastq2}"
        " out1={output.fastq1}"
        " out2={output.fastq2}"
        " &> {log}"


rule fastqc:
    input:
        fastq = "{prefix}.fastq.gz"
    output:
        html = "{prefix}_fastqc.html",
        zip = "{prefix}_fastqc.zip"
    log: "{prefix}_fastqc.log"
    singularity: fastqc
    threads: 2
    shell:
        "fastqc"
        " --threads {threads}"
        " {input.fastq}"
        " &> {log}"


rule kraken2:
    input:
        fastq1 = "fastqs/{sample}_1.filtered.fastq.gz",
        fastq2 = "fastqs/{sample}_2.filtered.fastq.gz"
    output:
        report = "kraken2/{sample}.report",
        unclassified1 = temp("kraken2/{sample}.unclassified_1.fastq"),
        unclassified2 = temp("kraken2/{sample}.unclassified_2.fastq"),
        unclassified1gz = "kraken2/{sample}.unclassified_1.fastq.gz",
        unclassified2gz = "kraken2/{sample}.unclassified_2.fastq.gz",
    log: "kraken2/{sample}.log"
    singularity: kraken2
    threads: 10
    params:
        db = kraken_db,
        unclassified_template = lambda wildcards: f"kraken2/{wildcards.sample}.unclassified#.fastq"
    shell:
        "kraken2"
        " --db {params.db}"
        " --report {output.report}"
        " --paired"
        " --unclassified-out {params.unclassified_template}"
        " --threads {threads}"
        " {input.fastq1} {input.fastq2}"
        " &> {log}"
        " && "
        "gzip -c {output.unclassified1} > {output.unclassified1gz}"
        " && "
        "gzip -c {output.unclassified2} > {output.unclassified2gz}"


rule multiqc:
    input:
        expand("kraken2/{sample}.report", sample=samples),
        expand("fastqs/{sample}_{nr}.filtered_fastqc.zip", sample=samples, nr=[1,2]),
        expand("fastqs/{sample}_{nr}_fastqc.zip", sample=samples, nr=[1,2]),
        expand("kraken2/{sample}.unclassified_{nr}_fastqc.zip", sample=samples, nr=[1,2]),
    output:
        html = "multiqc_report.html",
        data = directory("multiqc_data"),
    log: "multiqc_report.html.log"
    singularity: multiqc
    shell:
        "multiqc -m kraken -m fastqc -m bbduk ."
        " -c multiqc_config.yaml"
        #" --cl-config 'kraken: {{top_n: 25}}'"
        "&> {log}"
