"""
Snakemake file for downstream analysis of full Qiagen REPLI-g libraries.

load modules:

    ml bioinfo-tools snakemake

sbatch command:
    
    sbatch -A ngi2016004 -J down_q -n 11 -p core -t 1-00:00:00 --wrap "snakemake -p -j 11 --use-singularity -k --rerun-incomplete" --mail-user phojer@kth.se --mail-type ALL
"""

from snakemake.utils import min_version

min_version("6.0")

configfile: "workflow_config.yaml"


wildcard_constraints:
    sample = "|".join(config["samples"]),


rule all:
    input:
        "multiqc_report.html",
        expand("mosdepth_100kb/bedgraph/{sample}.regions.bedgraph", sample=config["samples"]),


module main_workflow:
    snakefile:
        # here, plain paths, URLs and the special markers for code hosting providers (see below) are possible.
        "../../downsample_qc/downstream_qc/Snakefile"
    config: config

use rule * from main_workflow exclude all as main_*
